name: b

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
        run: |
          cmd /c res\Downloads.bat
          cmd /c python res\setup.py

      - name: Time Counter
        run: cmd /c loop.bat
