name: b

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://github.com/noob-lol/a2/raw/main/res/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Setup
        env:
          WEBHOOK: ${{ secrets.WEBHOOK }}
        run: |
          cmd /c python setup.py
          cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
