name: ts win (A)

on:
  workflow_dispatch:
    inputs:
      test_mode: { description: "Run 5-minute test loop", type: boolean, default: false }
      runtime_minutes: { description: "Runtime in minutes (max 360; capped to 355)", default: "355" }
      loops: { description: "How many handoffs (0 = infinite)", default: "0" }

concurrency:
  group: tailscale-rdp-singleton
  cancel-in-progress: false

jobs:
  call-common:
    uses: ./.github/workflows/ts-common.yml
    with:
      test_mode: ${{ inputs.test_mode }}
      runtime_minutes: ${{ inputs.runtime_minutes }}
      loops: ${{ inputs.loops }}
      caller: "A"
    secrets:
      RDP_USER: ${{ secrets.RDP_USER }}
      RDP_PASS: ${{ secrets.RDP_PASS }}
      TS_AUTHKEY: ${{ secrets.TS_AUTHKEY }}
      TS_HOSTNAME: ${{ secrets.TS_HOSTNAME }}
